# Generated by Django 4.0.2 on 2022-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('posttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('request_url', models.URLField(max_length=255)),
            ],
        ),
    ]
